### ISSUE TITLE
Adpater throws error messages about iterations

### ISSUE THREAD

**Issue by mediaDS** [iobroker-community-adapters/ioBroker.coronavirus-statistics#118]
**Describe the bug**  
See log. Looks like a bug to me. Happens after updating to 0.6.2

**Expected behavior**  
A working adapter.

**Versions:**  
 - Adapter version: 0.6.2
 - JS-Controller version: 3.1.6
 - Node version: 12.19.0
 - Operating system: Linux arm

**Screenshots & Logfiles**  

```
2020-11-04 10:00:56.700 - error: coronavirus-statistics.0 (14707) [germanyFederalStates] error: values.features is not iterable, stack: TypeError: values.features is not iterable
--
at germanyBundersland (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:302:35)
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async Covid19.onReady (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:529:5)
2020-11-04 10:00:56.710 - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2020-11-04 10:00:56.711 - error: coronavirus-statistics.0 (14707) unhandled promise rejection: Cannot read property 'captureException' of undefined
2020-11-04 10:00:56.712 - error: coronavirus-statistics.0 (14707) TypeError: Cannot read property 'captureException' of undefined
at Covid19.errorHandling (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:686:37)
at germanyBundersland (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:389:11)
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async Covid19.onReady (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:529:5)
2020-11-04 10:00:57.263 - info: coronavirus-statistics.0 (14707) terminating
2020-11-04 10:00:57.266 - info: coronavirus-statistics.0 (14707) Terminated (NO_ERROR): Without reason
2020-11-04 10:00:57.802 - info: host.Casper instance system.adapter.coronavirus-statistics.0 terminated with code 0 (NO_ERROR)


```

**Comment by DutchmanNL** [comment]
solved in 0.6.3 https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/e1bfdbcc11a7d11fe5ab3f0091d8b901e0f3d3b4
