### ISSUE TITLE
No update anymore and errors in log

### ISSUE THREAD

**Issue by mediaDS** [iobroker-community-adapters/ioBroker.coronavirus-statistics#143]
No updates for 24 hours now. Some continous errors in the logs:

```
2020-12-30 09:41:37.981 - info: host.Casper stopInstance system.adapter.coronavirus-statistics.0 (force=false, process=true)
2020-12-30 09:41:37.985 - info: host.Casper stopInstance canceled schedule system.adapter.coronavirus-statistics.0
2020-12-30 09:41:41.100 - info: host.Casper instance scheduled system.adapter.coronavirus-statistics.0 */55 * * * *
2020-12-30 09:41:41.177 - info: host.Casper instance system.adapter.coronavirus-statistics.0 started with pid 7645
2020-12-30 09:41:44.000 - error: coronavirus-statistics.0 (7645) coronavirus-statistics.0 already running
2020-12-30 09:41:44.006 - warn: coronavirus-statistics.0 (7645) Terminated (ADAPTER_ALREADY_RUNNING): Without reason
2020-12-30 09:41:44.591 - error: host.Casper instance system.adapter.coronavirus-statistics.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
2020-12-30 09:45:00.147 - info: host.Casper instance system.adapter.dwd.0 started with pid 11332
2020-12-30 09:45:03.456 - info: dwd.0 (11332) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
2020-12-30 09:45:03.482 - info: dwd.0 (11332) starting. Version 2.5.2 in /opt/iobroker/node_modules/iobroker.dwd, node: v12.20.0, js-controller: 3.1.6
2020-12-30 09:45:04.224 - info: host.Casper instance system.adapter.daswetter.0 started with pid 11372
2020-12-30 09:45:06.693 - info: daswetter.0 (11372) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
2020-12-30 09:45:06.720 - info: daswetter.0 (11372) starting. Version 3.0.4 in /opt/iobroker/node_modules/iobroker.daswetter, node: v12.20.0, js-controller: 3.1.6
2020-12-30 09:45:09.936 - info: dwd.0 (11332) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2020-12-30 09:45:10.473 - info: host.Casper instance system.adapter.dwd.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2020-12-30 09:45:31.848 - info: daswetter.0 (11372) got wrong data structure! trying to repair...
2020-12-30 09:45:32.561 - info: host.Casper stopInstance system.adapter.coronavirus-statistics.0 (force=false, process=false)
2020-12-30 09:45:32.563 - info: host.Casper stopInstance canceled schedule system.adapter.coronavirus-statistics.0
2020-12-30 09:45:35.625 - info: host.Casper instance scheduled system.adapter.coronavirus-statistics.0 */55 */2 * * *
2020-12-30 09:45:35.694 - info: host.Casper instance system.adapter.coronavirus-statistics.0 started with pid 11992
2020-12-30 09:45:38.713 - error: coronavirus-statistics.0 (11992) coronavirus-statistics.0 already running
2020-12-30 09:45:38.721 - warn: coronavirus-statistics.0 (11992) Terminated (ADAPTER_ALREADY_RUNNING): Without reason
2020-12-30 09:45:39.295 - error: host.Casper instance system.adapter.coronavirus-statistics.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
2020-12-30 09:45:41.839 - info: daswetter.0 (11372) Terminated (NO_ERROR): Without reason

```

Platform linux
Betriebssystem linux
Architektur arm64
CPUs 4
Geschwindigkeit 1296 MHz
Modell Odroid
RAM 1.94 GB
Node.js v12.20.0
NPM 6.14.8
Adapter version 0.6.4

**Comment by DutchmanNL** [comment]
cannot reproduce, did you try to reboot your system ?

**Comment by mediaDS** [comment]
First you comment and then you close it at the same time? Funny. Anyway, yes, I did reboot - seems to work now but will observe it closer. I hope I don't have to reboot my system every time you update your adpater.

**Comment by DutchmanNL** [comment]
> First you comment and then you close it at the same time? Funny. Anyway, yes, I did reboot - seems to work now but will observe it closer. I hope I don't have to reboot my system every time you update your adpater.

I closed it as its not an adapter related bug .... :)
It can happen with node-processes that they are not closed properly, there is nothing I can d about it by code and its not reproducible (only in certain circumstances mostly after hangups or non-right handled reboots or ioBroker stops).

If at all, this would be an issue for the JS-controller to close or reboot the process correctly instead of throwing this warning.
Code itself is closing (terminating) the proces at any time, see : 

https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/blob/master/main.js#L622-L629

**Comment by mediaDS** [comment]
I rebootet and get this in the logs on every update with latest adpater:

```
2021-01-04 18:55:35.772 - error: coronavirus-statistics.0 (30052) [germanyFederalStates] error: Cannot read property '2' of null, stack: TypeError: Cannot read property '2' of null
--
at getInfos (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:780:80)
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async Covid19.getGermanyVaccinationData (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:796:27)
at async germanyBundersland (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:312:37)
at async Covid19.onReady (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:615:5)
2021-01-04 18:55:35.776 - error: coronavirus-statistics.0 (30052) [onReady] error: Cannot read property 'captureException' of undefined, stack: TypeError: Cannot read property 'captureException' of undefined
at Covid19.errorHandling (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:843:37)
at germanyBundersland (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:470:11)
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-01-04 18:55:35.780 - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-01-04 18:55:35.781 - error: coronavirus-statistics.0 (30052) unhandled promise rejection: Cannot read property 'captureException' of undefined
2021-01-04 18:55:35.783 - error: coronavirus-statistics.0 (30052) TypeError: Cannot read property 'captureException' of undefined
at Covid19.errorHandling (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:843:37)
at Covid19.onReady (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:627:9)
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-01-04 18:55:36.294 - info: coronavirus-statistics.0 (30052) terminating
2021-01-04 18:55:36.298 - info: coronavirus-statistics.0 (30052) Terminated (NO_ERROR): Without reason
2021-01-04 18:55:37.426 - info: host.Casper instance system.adapter.coronavirus-statistics.0 terminated with code 0 (NO_ERROR)

```

**Comment by DutchmanNL** [comment]
Update zo most resems Version
