### ISSUE TITLE
js-controller 3.2.x - Error features is not iterable

### ISSUE THREAD

**Issue by Feuer-sturm** [iobroker-community-adapters/ioBroker.coronavirus-statistics#158]
Mit dem js-controller 3.2.7 kam heute Abend folgender Fehler. Er trat bisher einmalig auf.
Adapter "COVID-19 live information" v0.6.7
js-controller: 3.2.7
node: 12.18.3 
nodejs: v12.18.3
npm: 6.14.6 
Admin: 4.2.1 

```
coronavirus-statistics.0	2021-01-17 22:45:45.398	info	(17994) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
coronavirus-statistics.0	2021-01-17 22:45:38.861	error	at Covid19.onReady (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:599:5)
coronavirus-statistics.0	2021-01-17 22:45:38.861	error	at processTicksAndRejections (internal/process/task_queues.js:97:5)
coronavirus-statistics.0	2021-01-17 22:45:38.861	error	at runMicrotasks (<anonymous>)
coronavirus-statistics.0	2021-01-17 22:45:38.861	error	at germanyBundersland (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:314:35)
coronavirus-statistics.0	2021-01-17 22:45:38.861	error	(17994) [germanyFederalStates] error: values.features is not iterable, stack: TypeError: values.features is not iterable
```

**Comment by DutchmanNL** [comment]
Danke, Fehler gefunden machen morgen commit

**Comment by DutchmanNL** [comment]
[Fixed release v0.6.8](https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/c00c0f39ef480e5d9ca754b3bcea713fc5eb0368)
